
package com.sap.document.sap.rfc.functions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZMM_WS_CONSULTA_MOVIMIENTO", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/home/mariano/work/Huella/soaphuella/sap/zmm_ws_consulta_movimiento.wsdl")
public class ZMMWSCONSULTAMOVIMIENTO_Service
    extends Service
{

    private final static URL ZMMWSCONSULTAMOVIMIENTO_WSDL_LOCATION;
    private final static WebServiceException ZMMWSCONSULTAMOVIMIENTO_EXCEPTION;
    private final static QName ZMMWSCONSULTAMOVIMIENTO_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_WS_CONSULTA_MOVIMIENTO");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/home/mariano/work/Huella/soaphuella/src/sap/zmm_ws_consulta_movimiento.wsdl");
            url = new URL("http://srv-s4-asq.pdm.local:8000/sap/bc/srt/wsdl/flv_10002A111AD1/srvc_url/sap/bc/srt/rfc/sap/zmm_ws_consulta_movimiento/400/zmm_ws_consulta_movimiento/zmm_ws_consulta_movimiento?sap-client=400");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZMMWSCONSULTAMOVIMIENTO_WSDL_LOCATION = url;
        ZMMWSCONSULTAMOVIMIENTO_EXCEPTION = e;
    }

    public ZMMWSCONSULTAMOVIMIENTO_Service() {
        super(__getWsdlLocation(), ZMMWSCONSULTAMOVIMIENTO_QNAME);
    }

    public ZMMWSCONSULTAMOVIMIENTO_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZMMWSCONSULTAMOVIMIENTO_QNAME, features);
    }

    public ZMMWSCONSULTAMOVIMIENTO_Service(URL wsdlLocation) {
        super(wsdlLocation, ZMMWSCONSULTAMOVIMIENTO_QNAME);
    }

    public ZMMWSCONSULTAMOVIMIENTO_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZMMWSCONSULTAMOVIMIENTO_QNAME, features);
    }

    public ZMMWSCONSULTAMOVIMIENTO_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZMMWSCONSULTAMOVIMIENTO_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZMMWSCONSULTAMOVIMIENTO
     */
    @WebEndpoint(name = "ZMM_WS_CONSULTA_MOVIMIENTO")
    public ZMMWSCONSULTAMOVIMIENTO getZMMWSCONSULTAMOVIMIENTO() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_WS_CONSULTA_MOVIMIENTO"), ZMMWSCONSULTAMOVIMIENTO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMMWSCONSULTAMOVIMIENTO
     */
    @WebEndpoint(name = "ZMM_WS_CONSULTA_MOVIMIENTO")
    public ZMMWSCONSULTAMOVIMIENTO getZMMWSCONSULTAMOVIMIENTO(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_WS_CONSULTA_MOVIMIENTO"), ZMMWSCONSULTAMOVIMIENTO.class, features);
    }

    /**
     * 
     * @return
     *     returns ZMMWSCONSULTAMOVIMIENTO
     */
    @WebEndpoint(name = "ZMM_WS_CONSULTA_MOVIMIENTO_soap12")
    public ZMMWSCONSULTAMOVIMIENTO getZMMWSCONSULTAMOVIMIENTOSoap12() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_WS_CONSULTA_MOVIMIENTO_soap12"), ZMMWSCONSULTAMOVIMIENTO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMMWSCONSULTAMOVIMIENTO
     */
    @WebEndpoint(name = "ZMM_WS_CONSULTA_MOVIMIENTO_soap12")
    public ZMMWSCONSULTAMOVIMIENTO getZMMWSCONSULTAMOVIMIENTOSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "ZMM_WS_CONSULTA_MOVIMIENTO_soap12"), ZMMWSCONSULTAMOVIMIENTO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZMMWSCONSULTAMOVIMIENTO_EXCEPTION!= null) {
            throw ZMMWSCONSULTAMOVIMIENTO_EXCEPTION;
        }
        return ZMMWSCONSULTAMOVIMIENTO_WSDL_LOCATION;
    }

}
