
package wsserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HuellaServer", targetNamespace = "http://wsserver/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HuellaServer {


    /**
     * 
     * @param hasta
     * @param desde
     * @return
     *     returns wsserver.AnimalArray
     */
    @WebMethod
    @WebResult(name = "animal", partName = "animal")
    @Action(input = "http://wsserver/HuellaServer/consultaMovimientoRequest", output = "http://wsserver/HuellaServer/consultaMovimientoResponse")
    public AnimalArray consultaMovimiento(
        @WebParam(name = "desde", partName = "desde")
        String desde,
        @WebParam(name = "hasta", partName = "hasta")
        String hasta);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsserver/HuellaServer/altaRequest", output = "http://wsserver/HuellaServer/altaResponse")
    public String alta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsserver/HuellaServer/bajaRequest", output = "http://wsserver/HuellaServer/bajaResponse")
    public String baja(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://wsserver/HuellaServer/modificacionRequest", output = "http://wsserver/HuellaServer/modificacionResponse")
    public String modificacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
