
package wsserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HuellaServerService", targetNamespace = "http://wsserver/", wsdlLocation = "http://localhost:1212/huella?wsdl")
public class HuellaServerService
    extends Service
{

    private final static URL HUELLASERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HUELLASERVERSERVICE_EXCEPTION;
    private final static QName HUELLASERVERSERVICE_QNAME = new QName("http://wsserver/", "HuellaServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1212/huella?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HUELLASERVERSERVICE_WSDL_LOCATION = url;
        HUELLASERVERSERVICE_EXCEPTION = e;
    }

    public HuellaServerService() {
        super(__getWsdlLocation(), HUELLASERVERSERVICE_QNAME);
    }

    public HuellaServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HUELLASERVERSERVICE_QNAME, features);
    }

    public HuellaServerService(URL wsdlLocation) {
        super(wsdlLocation, HUELLASERVERSERVICE_QNAME);
    }

    public HuellaServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HUELLASERVERSERVICE_QNAME, features);
    }

    public HuellaServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HuellaServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HuellaServer
     */
    @WebEndpoint(name = "HuellaServerPort")
    public HuellaServer getHuellaServerPort() {
        return super.getPort(new QName("http://wsserver/", "HuellaServerPort"), HuellaServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HuellaServer
     */
    @WebEndpoint(name = "HuellaServerPort")
    public HuellaServer getHuellaServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsserver/", "HuellaServerPort"), HuellaServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HUELLASERVERSERVICE_EXCEPTION!= null) {
            throw HUELLASERVERSERVICE_EXCEPTION;
        }
        return HUELLASERVERSERVICE_WSDL_LOCATION;
    }

}
