
package wsserver;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HuellaServer", targetNamespace = "http://wsserver/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HuellaServer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<wsserver.Animal>
     */
    @WebMethod
    @WebResult(name = "animal", targetNamespace = "")
    @RequestWrapper(localName = "consultaMovimiento", targetNamespace = "http://wsserver/", className = "wsserver.ConsultaMovimiento")
    @ResponseWrapper(localName = "consultaMovimientoResponse", targetNamespace = "http://wsserver/", className = "wsserver.ConsultaMovimientoResponse")
    @Action(input = "http://wsserver/HuellaServer/consultaMovimientoRequest", output = "http://wsserver/HuellaServer/consultaMovimientoResponse")
    public List<Animal> consultaMovimiento(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alta", targetNamespace = "http://wsserver/", className = "wsserver.Alta")
    @ResponseWrapper(localName = "altaResponse", targetNamespace = "http://wsserver/", className = "wsserver.AltaResponse")
    @Action(input = "http://wsserver/HuellaServer/altaRequest", output = "http://wsserver/HuellaServer/altaResponse")
    public String alta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "baja", targetNamespace = "http://wsserver/", className = "wsserver.Baja")
    @ResponseWrapper(localName = "bajaResponse", targetNamespace = "http://wsserver/", className = "wsserver.BajaResponse")
    @Action(input = "http://wsserver/HuellaServer/bajaRequest", output = "http://wsserver/HuellaServer/bajaResponse")
    public String baja(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificacion", targetNamespace = "http://wsserver/", className = "wsserver.Modificacion")
    @ResponseWrapper(localName = "modificacionResponse", targetNamespace = "http://wsserver/", className = "wsserver.ModificacionResponse")
    @Action(input = "http://wsserver/HuellaServer/modificacionRequest", output = "http://wsserver/HuellaServer/modificacionResponse")
    public String modificacion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
